In [12]:
import torch
import numpy as np

Создайте случайный FloatTensor размера 3x4x5

In [13]:
tsr = torch.FloatTensor(3,4,5)
tsr

tensor([[[2.5959e-36, 0.0000e+00, 2.9427e-43, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.8788e+31, 1.7220e+22, 2.1715e-18, 3.3980e+21, 1.6613e-07],
         [2.6804e-09, 2.1888e+23, 1.6874e-07, 6.7061e+22, 4.1912e+21]],

        [[6.7644e+22, 1.0499e-08, 1.4580e-19, 1.1495e+24, 3.0881e+29],
         [1.5766e-19, 4.6304e+27, 7.2707e+31, 7.1536e+22, 3.3803e-18],
         [2.0552e+32, 1.8755e+28, 3.1093e-18, 2.0552e+32, 1.8755e+28],
         [3.1093e-18, 1.2845e+31, 1.8395e+25, 6.1963e-04, 8.4241e-07]],

        [[8.3650e+20, 1.0082e-08, 5.3183e+22, 6.7448e-10, 2.6852e-06],
         [1.6708e-07, 6.7444e-10, 3.0547e-18, 1.1963e+22, 3.1097e-18],
         [9.4370e-09, 1.0129e-11, 6.3008e-10, 1.6515e-07, 6.7598e-04],
         [2.5957e-06, 1.0432e-08, 2.3072e-12, 7.2646e+22, 7.2250e+28]]])

Выведите его форму (shape)

In [14]:
tsr.shape

torch.Size([3, 4, 5])

Приведите его к форме 6 X 10

In [15]:
tsr1 = tsr.reshape(6, 10)
tsr1

tensor([[2.5959e-36, 0.0000e+00, 2.9427e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.8788e+31, 1.7220e+22, 2.1715e-18, 3.3980e+21, 1.6613e-07, 2.6804e-09,
         2.1888e+23, 1.6874e-07, 6.7061e+22, 4.1912e+21],
        [6.7644e+22, 1.0499e-08, 1.4580e-19, 1.1495e+24, 3.0881e+29, 1.5766e-19,
         4.6304e+27, 7.2707e+31, 7.1536e+22, 3.3803e-18],
        [2.0552e+32, 1.8755e+28, 3.1093e-18, 2.0552e+32, 1.8755e+28, 3.1093e-18,
         1.2845e+31, 1.8395e+25, 6.1963e-04, 8.4241e-07],
        [8.3650e+20, 1.0082e-08, 5.3183e+22, 6.7448e-10, 2.6852e-06, 1.6708e-07,
         6.7444e-10, 3.0547e-18, 1.1963e+22, 3.1097e-18],
        [9.4370e-09, 1.0129e-11, 6.3008e-10, 1.6515e-07, 6.7598e-04, 2.5957e-06,
         1.0432e-08, 2.3072e-12, 7.2646e+22, 7.2250e+28]])

Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

In [33]:
b = np.array([1, 4, 2, 2, 1])
c = tsr @ b
c

tensor([[2.5959e-36, 0.0000e+00, 1.8788e+31, 1.0138e+24],
        [3.0881e+29, 1.4543e+32, 6.1665e+32, 5.1380e+31],
        [1.0720e+23, 2.3926e+22, 6.7632e-04, 7.2250e+28]], dtype=torch.float64)

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [24]:
tsr2 = tsr1 @ tsr1.T
print(tsr2)
tsr2.shape

tensor([[0.0000e+00, 4.8771e-05, 1.7560e-13, 5.3351e-04, 2.1715e-15, 2.3822e-44],
        [4.8771e-05,        inf,        inf,        inf,        inf,        inf],
        [1.7560e-13,        inf,        inf,        inf,        inf,        inf],
        [5.3351e-04,        inf,        inf,        inf,        inf, 4.8754e+25],
        [2.1715e-15,        inf,        inf,        inf,        inf,        inf],
        [2.3822e-44,        inf,        inf, 4.8754e+25,        inf,        inf]])


torch.Size([6, 6])

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [26]:
xzt = torch.Tensor([1, 0.5, 2])
xzt.requires_grad = True
y = xzt[0]**3 + xzt[1] - 75 * xzt[2]

In [27]:
y.backward()
xzt.grad

tensor([  3.,   1., -75.])

Создайте единичный тензор размера 5x6

In [28]:
tsr3 = torch.ones(5, 6)
tsr3

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

Переведите его в формат numpy

In [29]:
tsr3.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
Посчитайте 

In [38]:
tsr3.grad
w1 = torch.tensor([0.417], requires_grad=True)
y = tsr3*w1 - 2 * tsr3 ** 2 + 5
y.backward(tsr3)
print(y)

tensor([[3.4170, 3.4170, 3.4170, 3.4170, 3.4170, 3.4170],
        [3.4170, 3.4170, 3.4170, 3.4170, 3.4170, 3.4170],
        [3.4170, 3.4170, 3.4170, 3.4170, 3.4170, 3.4170],
        [3.4170, 3.4170, 3.4170, 3.4170, 3.4170, 3.4170],
        [3.4170, 3.4170, 3.4170, 3.4170, 3.4170, 3.4170]],
       grad_fn=<AddBackward0>)
